function template =getTemplate_3d(feature,bb_3d)
bb_3d =round(bb_3d);
template = feature(bb_3d(2):min(size(feature,1),bb_3d(2)+bb_3d(5)),...
                   bb_3d(1):min(size(feature,2),bb_3d(1)+bb_3d(4)),...
                   bb_3d(3):min(size(feature,3),bb_3d(3)+bb_3d(6)),...
                   :);

end